### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by sj-mmxm** [kalvin-eliazord/CS2_Internal_Trainer#1]
Injects fine but none of the features work

**Comment by kalvin-eliazord** [comment]
Hi @sj-mmxm, 
If it compiles and the console appear without pointers error, it might be your configuration properties or antivirus:
- **Deactivate antivirus** because it could block features,
- Open configuration properties and go to "**Linker->ManisfestFile**" (see screen below)
- Check if "**UAC Execution Level**" is sets to "**requireAdministrator (/level='requireAdministrator')**"

Compile again and tell me if it's working 

![image](https://github.com/kalvin-eliazord/CS2_Internal_Trainer/assets/61147281/fb707df5-3579-4f52-9674-b55dfbfb5238)

**Comment by sj-mmxm** [comment]
Hello, thanks for the response. I will try this now

**Comment by sj-mmxm** [comment]
![image](https://github.com/kalvin-eliazord/CS2_Internal_Trainer/assets/168670418/803a1cbc-86e2-422d-b94f-6bd1e2ebdd52)
![image](https://github.com/kalvin-eliazord/CS2_Internal_Trainer/assets/168670418/5842b242-b697-4d42-a0f9-4afb161f5691)
![image](https://github.com/kalvin-eliazord/CS2_Internal_Trainer/assets/168670418/e9edafd1-43f3-438c-bae7-374c3ceb40b5)

The aimbot seems to be working now, although its quite buggy. 

Was the cheat just updated? did you remove ESP? Lol

**Comment by sj-mmxm** [comment]
Do you maybe want to shoot me your discord or something? Id love to expand this project, maybe add a GUI?

Let me know :)

**Comment by kalvin-eliazord** [comment]
Yeah, I had to remove this "feature" because it wasn't ready yet, add me on discord: not_leet_yet
